{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Sales\",\"Product\",\"All_measures\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.1177.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-IN",
    "cultures": [
      {
        "name": "en-IN",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "ee1014fc-3aa2-4bd8-88a4-e7847b78573c",
        "fromColumn": "PRODUCT ID",
        "fromTable": "Sales",
        "toColumn": "PRODUCT ID",
        "toTable": "Product"
      },
      {
        "name": "ca9218a3-4a0f-4c4d-b45f-07b34fde58b1",
        "fromColumn": "DATE",
        "fromTable": "Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_82faf180-b9b3-49b8-ab89-c4f206793086"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "DateTableTemplate_699d92b0-3224-4e88-949d-09c92d147959",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6de43aae-e2fb-4d4e-8f7c-ef7f7bcf08ff",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2fbc0b4a-d022-4f49-98f8-061db3de4295",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0eb1e4d6-cbfd-440d-92cf-0b74ba039458",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e8dafecc-4d4a-47d0-b9a8-81f59d37581b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "706a4392-7247-4bcb-a2b3-c95e3ed56584",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "63b22b9b-9211-4db5-bcf1-d9ee3164bf70",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d6cf01ca-8a5e-4cf3-b536-cbbc11b2d05f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4198d9f8-1b08-4ed8-ad2e-6a6e49c9bc52",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9e35dfde-359f-45bb-89c6-166152fd50cf",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f747583c-5408-49e3-a75d-83f2e810b7a5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "eb35080d-5b2a-4cc9-a5ce-5c557b138db5",
                "ordinal": 3
              }
            ],
            "lineageTag": "2b7a3342-7e4b-4f47-a97b-155a86bf0373"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3220a6e5-8ea6-4fe7-958e-c609be9adb0e",
        "partitions": [
          {
            "name": "DateTableTemplate_699d92b0-3224-4e88-949d-09c92d147959-6fa932bb-03d5-4288-8aa8-a9a486f3d816",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3aaa69db-776b-49c3-95ba-283230ca425c",
            "sourceColumn": "DATE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_82faf180-b9b3-49b8-ab89-c4f206793086"
                },
                "isDefault": true,
                "relationship": "ca9218a3-4a0f-4c4d-b45f-07b34fde58b1"
              }
            ]
          },
          {
            "name": "PRODUCT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f40d81d6-fec0-4d67-acdc-8c5f1d7e5b13",
            "sourceColumn": "PRODUCT ID",
            "summarizeBy": "none"
          },
          {
            "name": "QUANTITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8410c456-4b4f-4078-939c-ca018ded9eea",
            "sourceColumn": "QUANTITY",
            "summarizeBy": "sum"
          },
          {
            "name": "SALE TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75e39a27-ff8e-4472-a336-b9c79ab3357a",
            "sourceColumn": "SALE TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "PAYMENT MODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44749584-48a7-4d67-a969-10d4e392c742",
            "sourceColumn": "PAYMENT MODE",
            "summarizeBy": "none"
          },
          {
            "name": "DISCOUNT %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1132ac1a-6fa7-415e-af48-eaa414752b67",
            "sourceColumn": "DISCOUNT %",
            "summarizeBy": "sum"
          },
          {
            "name": "Buying Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED(Product[BUYING PRIZE])*(Sales[QUANTITY])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "0f5684e6-3c95-4600-ad7f-af335a268894",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Selling Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "(Sales[QUANTITY])*RELATED(Product[SELLING PRICE])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "12d6bfed-1783-4164-a97b-bc51c48a4b18",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "893c61d9-f51b-4d6c-80a5-6eda10bad2ec",
        "partitions": [
          {
            "name": "Sales-09c7cdcc-6041-4d4a-84ec-32634d300a84",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DV CLASS\\EXCEL\\SESSION-7 ASSIGNMENTS\\Dashboard Test\\SALES DATA DASHBOARD 2022.xlsx\"), null, true),",
                "    SALES_DATA_Sheet = Source{[Item=\"SALES_DATA\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(SALES_DATA_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"DATE\", type date}, {\"PRODUCT ID\", type text}, {\"QUANTITY\", Int64.Type}, {\"SALE TYPE\", type text}, {\"PAYMENT MODE\", type text}, {\"DISCOUNT %\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PRODUCT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dad87eb7-0fca-4f55-aa0e-1b86d418e6d4",
            "sourceColumn": "PRODUCT ID",
            "summarizeBy": "none"
          },
          {
            "name": "PRODUCT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddc4863c-ad4f-4398-91d7-cd798eccd1cf",
            "sourceColumn": "PRODUCT",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9555c0a0-e47b-4c44-8ad3-a4f74b86d09e",
            "sourceColumn": "CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "UOM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f695b6e1-cc9c-4f43-b1d5-6dc1b961310e",
            "sourceColumn": "UOM",
            "summarizeBy": "none"
          },
          {
            "name": "BUYING PRIZE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a75659b9-9e37-49f3-b536-29ab9c23e5a6",
            "sourceColumn": "BUYING PRIZE",
            "summarizeBy": "none"
          },
          {
            "name": "SELLING PRICE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6f2853f9-3be6-44f7-9e99-5a2879f01021",
            "sourceColumn": "SELLING PRICE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8d40b614-758b-4fee-879c-7b6ff3a23c94",
        "partitions": [
          {
            "name": "Product-9131bc56-3e03-4d0a-b112-43b4b098f145",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DV CLASS\\EXCEL\\SESSION-7 ASSIGNMENTS\\Dashboard Test\\SALES DATA DASHBOARD 2022.xlsx\"), null, true),",
                "    PRODUCT_MASTER_Sheet = Source{[Item=\"PRODUCT_MASTER\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(PRODUCT_MASTER_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"PRODUCT ID\", type text}, {\"PRODUCT\", type text}, {\"CATEGORY\", type text}, {\"UOM\", type text}, {\"BUYING PRIZE\", Int64.Type}, {\"SELLING PRICE\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "All_measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "00bad151-2e68-4910-934d-be05b97f2881",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4fced863-aa66-4604-925f-0e00b5814eed",
        "measures": [
          {
            "name": "Total Buying Value",
            "expression": "SUM(Sales[Buying Value])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a6054308-4d7e-4221-b2d5-2f404184c865"
          },
          {
            "name": "Total Selling Value",
            "expression": "SUM(Sales[Selling Value])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "f7e35b2c-fc35-49d1-b49e-14f3ea8da707"
          },
          {
            "name": "Profit Margin",
            "expression": "[Total Selling Value]-[Total Buying Value]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "91c88c6e-4b02-4615-af2d-3b49b8ee594b"
          },
          {
            "name": "Profit %",
            "expression": "[Profit Margin]/[Total Buying Value]",
            "formatString": "0%;-0%;0%",
            "lineageTag": "58f62a14-8baf-4fa9-9260-b8444bf99a2e"
          }
        ],
        "partitions": [
          {
            "name": "All_measures-ff55be50-35dc-4ddc-b038-26e3bf0eff6c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_82faf180-b9b3-49b8-ab89-c4f206793086",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2836ade2-223d-4054-9577-539b0ee64fb4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba492ba5-6015-4869-811f-0e0a526ad2f6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e3e2a034-e011-408b-aa6b-5d0bb60f7356",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "977131f9-6e11-40b9-8900-4da6cc6aa621",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "29eb3b08-8a8c-4a28-a31e-9afd9e324951",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "eb072b57-8e5a-42ac-90bf-d60675d81632",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "070da302-c041-4804-aa9a-7bf29fb1282b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "be48949a-8c72-4e8c-b5b6-b01b32f841ca",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "bb4e91c9-3f49-47d6-a20a-4c4ea3b4ab95",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3ff769f9-e3b3-4022-9e74-d1ee93b65bc5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1f79c7b6-bb7b-412f-bf62-e891e160807d",
                "ordinal": 3
              }
            ],
            "lineageTag": "c4f64598-0934-4e4f-8930-0b3fa7911e8a"
          }
        ],
        "isHidden": true,
        "lineageTag": "6c7b7943-c3a0-4ae0-902f-65966902cf0f",
        "partitions": [
          {
            "name": "LocalDateTable_82faf180-b9b3-49b8-ab89-c4f206793086-1979bf93-8b30-491b-b4c4-9577d7405da4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sales'[DATE])), 1, 1), Date(Year(MAX('Sales'[DATE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}